spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demoProject
    username: shin
    password: 123
    driver-class-name: org.h2.Driver
  messages:
    basename: messages


  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
      format_sql: true
  ## 이메일 발송을 위한 설정 내용
  mail:
    host: smtp.gmail.com
    port: 587
    ## google 계정 정보
    username: {YOUR_GMAIL_ADDRESS}
    password: {YOUR_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 1800 # 1800초 (30분)이 세션 타임아웃 max시간 (최소는 10초)
      cookie:
        max-age: 1800
        http-only: true

logging.level:
  org.hibernate.SQL: debug

