spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demoProject
    username: shin
    password: 123
    driver-class-name: org.h2.Driver
  messages:
    basename: messages


  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
      format_sql: true

server:
  servlet:
    session:
      timeout: 1800 # 1800초 (30분)이 세션 타임아웃 max시간 (최소는 10초)
      cookie:
        max-age: 1800
        http-only: true

logging.level:
  org.hibernate.SQL: debug

